### ISSUE TITLE
Support reflection backend for SPIRV-Cross

### ISSUE THREAD

**Issue by jherico** [tgjones/shader-playground#32]
SPIRV-Cross will support outputting JSON formatted reflection data about a given shader in the next release with the `--reflect` option.  Can you add support to the app to output this as an option?

**Comment by tgjones** [comment]
For my own reference, here’s the related issue: https://github.com/KhronosGroup/SPIRV-Cross/issues/544

**Comment by tgjones** [comment]
Done! I chose to do it as an additional "output", rather than its own "language", because I think you always want JSON reflection *in addition* to the main shader output. Let me know if you can think of a better way of doing it.

<img width="934" alt="reflection" src="https://user-images.githubusercontent.com/102049/42102991-4a65e618-7bfa-11e8-8bd7-6565c86d32ca.PNG">
