### ISSUE TITLE
Exact version of glslang compiler?

### ISSUE THREAD

**Issue by hrydgard** [tgjones/shader-playground#42]
It currently says "trunk", but how often do you update it? Is it automated?

I wanted to report a bug in glslang that I discovered using the shader playground. Thought I'd also save myself the time to build a fresh glslang exe to see if it still repros, and if I know your build is fresh, the bug report will be valid :)

**Comment by tgjones** [comment]
Sorry for not replying before! It's not automated - so the compilers which are not properly versioned (glslang, dxc, etc.) are updated whenever I remember to update them. Based on your comment, I'm updating that to at least include the date that I updated it, so instead of just `trunk` it will show `trunk (2019-01-20)`.
